name: Run Python Tests

on:
  pull_request: 
    branches:
      - master

jobs:
  test:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt

      - name: Run Tests
        run: pytest
